---
resources:
- name: my-pipelines
  type: git
  source:
    uri: https://github.com/datianshi/concourse-task-modular

jobs:
- name: sample-job
  plan:
  - get: my-pipelines
  - task: task1
    file: my-pipelines/tasks/task1/task.yml
    input_mapping:
      pipeline: my-pipelines
    params:
      NAME: shaozhen
      PASSWORD: mypassword
  - task: task2
    file: my-pipelines/tasks/task2/task.yml
    input_mapping:
      pipeline: my-pipelines
      input: output-name-json
    params:
      ADDRESS: Texas
  - task: task3
    file: my-pipelines/tasks/task3/task.yml
    input_mapping:
      pipeline: my-pipelines
      input1: output-name-json
      input2: output-name-address-json
